# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 083d75cd94afd48d10e2ecd0c71953e0b20110e9bd113a0e5d1df45f535c60f6ee69461e12b09d0b3b3679e56820efd9b4de2d830a73b5326a9615517abacca3

test:
  secret_key_base: 561f3ab6d29cd450f5f69813b2170aca0a9b87c680ca733745ca5c017a14806e9db6f58dd3d780c9bf944bbcbf1b6dc07d97ddbe86a9258eaf33150fdd29e33a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
